create/destroy symlinks

diff --git a/scripts/dotfiles b/scripts/dotfiles
--- a/scripts/dotfiles
+++ b/scripts/dotfiles
@@ -12,3 +12,43 @@ log_warn() {
 log_error() {
   printf "\x1b[31m[error]\x1b[0m: ${1}\n"
 }
+create_symlink() {
+  local src="$1"
+  local dest="$2"
+
+  if [[ "$opt_silent" != "true" ]]; then
+    log_info "linking \'${src}\' -> \'${dest}\'"
+  fi
+
+  if [[ -e "$dest" ]]; then
+    if [[ "$opt_force" == "true" ]]; then
+      destroy_symlink "$dest"
+    else
+      if [[ "$opt_silent" != "true" ]]; then
+        log_warn "file \'${dest}\' already exists"
+      fi
+
+      return
+    fi
+  fi
+
+  # remove symlink on error
+  if ! ln -s "$src" "$dest" &>/dev/null; then
+    if [[ "$opt_silent" != "true" ]]; then
+      log_error "failed to link \'${src}\' to \'${dest}\'"
+    fi
+
+    destroy_symlink "$dest"
+    exit 1
+  fi
+}
+
+destroy_symlink() {
+  dest="$1"
+
+  if [[ "$opt_silent" != "true" ]]; then
+    log_info "deleting \'${dest}\'"
+  fi
+
+  rm -rf "$dest"
+}
